# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Date time'), (2, 'Date'), (3, 'Char'), (4, 'Integer'), (5, 'Float'), (6, 'File'), (7, 'Image'), (8, 'Text'), (9, 'Email'), (10, 'Dropdown')])),
                ('name', models.CharField(max_length=128)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dynamic_fields.Field')),
            ],
        ),
    ]
